# frozen_string_literal: true

require "yaml"
require "fileutils"

module PgKeeper
  # Serializes wizard-collected settings back to +pgkeeper.yml+.
  #
  # Two shapes are produced:
  #
  #   * {render_config} writes a complete, commented starter config for a host
  #     that has none yet.
  #   * {append_database} inserts one database into an *existing* file by
  #     targeted text surgery — it never re-serializes the whole document, so a
  #     hand-authored file keeps its comments and its `<%= ENV[...] %>`
  #     interpolations intact (round-tripping through Psych would resolve the
  #     ERB and strip every comment).
  #
  # Passwords are always rendered as an ENV reference, never inlined, matching
  # the "secrets come from the environment" convention the example config uses.
  module ConfigWriter
    module_function

    # Atomically write +content+ to +path+ (temp file + rename), creating parent
    # directories as needed, so a crash mid-write can't leave a truncated config.
    def write(path, content)
      dir = File.dirname(path)
      FileUtils.mkdir_p(dir)
      tmp = "#{path}.tmp.#{Process.pid}"
      File.write(tmp, content)
      File.rename(tmp, path)
      path
    end

    # The env var name a database's password is read from, e.g.
    # +PGKEEPER_APP_PRODUCTION_PASSWORD+.
    def password_env(db_name)
      slug = db_name.to_s.upcase.gsub(/[^A-Z0-9]+/, "_").gsub(/\A_+|_+\z/, "")
      "PGKEEPER_#{slug}_PASSWORD"
    end

    # Render one database as a YAML list item (2-space indented) given an ordered
    # hash of key => value. A +:password_env+ key is emitted as an ERB ENV
    # reference rather than a quoted string.
    def render_database(entry)
      lines = entry.filter_map do |key, value|
        next if value.nil?

        if key.to_s == "password_env"
          %(    password: <%= ENV["#{value}"] %>)
        else
          "    #{key}: #{scalar(value)}"
        end
      end
      lines[0] = lines[0].sub(/\A    /, "  - ")
      "#{lines.join("\n")}\n"
    end

    # Insert a rendered database entry as the first item under the existing
    # file's `databases:` list, preserving everything else verbatim. Raises
    # {ConfigError} when the file has no recognizable `databases:` block, so the
    # caller can fall back to printing the snippet for a manual paste.
    def append_database(text, entry_yaml)
      lines = text.lines
      idx = lines.index { |line| line.match?(/\A\s*databases:\s*(#.*)?\z/) }
      raise ConfigError, "could not find a `databases:` list to add to" if idx.nil?

      block = entry_yaml.end_with?("\n") ? entry_yaml : "#{entry_yaml}\n"
      lines.insert(idx + 1, reindent(block, list_indent(lines, idx)))
      lines.join
    end

    # A complete starter config: workdir, a global schedule, one database, one
    # local storage target, sensible compression + retention defaults.
    def render_config(workdir:, schedule:, database:, backup_path:, compression: "gzip")
      <<~YAML
        # PgKeeper configuration — generated by `pgkeeper connect`.
        #
        # Secrets belong in the environment, not this file: password fields below
        # interpolate an env var via ERB. Export it before running pgkeeper.
        # Docs: https://github.com/devcamke/pgkeeper

        workdir: #{scalar(workdir)}

        # When backups run. Accepts cron ("15 3 * * *"), natural language
        # ("every day at 03:15"), or shorthands ("hourly", "daily at 03:15").
        # Activate with `pgkeeper schedule install` (cron/systemd) or run
        # `pgkeeper daemon` in a container. A per-database `schedule:` overrides this.
        schedule: #{scalar(schedule)}

        # Compression of the artifact: none | gzip | zip | zstd. `custom`/`directory`
        # dumps are already compressed, so this is skipped for them automatically.
        compression: #{scalar(compression)}

        databases:
        #{render_database(database).chomp}

        # Where backups are stored. Every run fans out to all destinations; each is
        # tracked independently. Add s3/dropbox/google_drive/sharepoint targets here —
        # see config/pgkeeper.example.yml for the full set.
        storage:
          - type: local
            path: #{scalar(backup_path)}

        # Keep this many backups per destination (a dropped policy keeps everything).
        retention:
          keep_daily: 7
          keep_weekly: 4
          keep_monthly: 6
      YAML
    end

    # -- helpers ------------------------------------------------------------

    # Render a Ruby scalar as a safe YAML scalar. We route through Psych so
    # strings that need quoting (booleans-as-words, leading digits, colons) are
    # escaped correctly, then strip the document header it adds.
    def scalar(value)
      YAML.dump(value).sub(/\A---\s*/, "").chomp
    end

    # Indentation (number of leading spaces before the `-`) of the existing list
    # under `databases:`, so an appended entry lines up. Defaults to 2 when the
    # list is currently empty.
    def list_indent(lines, databases_idx)
      lines[(databases_idx + 1)..]&.each do |line|
        next if line.strip.empty?

        m = line.match(/\A( *)-\s/)
        return m[1].length if m

        break # first content line isn't a list item; stop looking
      end
      2
    end

    # Re-indent a 2-space-based rendered entry to +indent+ spaces.
    def reindent(block, indent)
      return block if indent == 2

      shift = indent - 2
      return block.gsub(/^/, " " * shift) if shift.positive?

      block.gsub(/^ {1,#{-shift}}/, "")
    end
  end
end
